Dockerfile

Hi Paul, 
First be aware that I'm not yet very familiar with building Erlang.
We've been facing issues while compiling rabbitmq dependencies when working with Elixir 
```
/app/deps/rabbit_common/src/rabbit_ct_broker_helpers.erl:19: can't find include lib "common_test/include/ct.hrl"
```
After investigating, we've found that it boils down to `common_tests` being skipped when Erlang is compiled in `alpine-erlang`. Re-adding leads to just a 3mb larger image. 
I don't know if that makes sense to merge this, given my understanding is: 
- that using releases (with `distillery` thanks for writing it 💪  ) would negates the problem in the problem in the first place as we'd be compiling locally, where we'd have `common_test` included and then just placing the release in the docker image.
- still, …

Remove --without-common_test flag

---

Dockerfile

I'd like to propose to add dialyzer, as it's widely used in development and your alpine-elixir image is based on this erlang image.
The compressed image size difference is ~1 MB ([52 MB](https://hub.docker.com/r/arnodirlam/alpine-erlang/tags/) forked image as compared to [51 MB](https://hub.docker.com/r/bitwalker/alpine-erlang/tags/)), so it's probably not worth the hassle to maintain a separate image tag just for dialyzer inclusion, IMHO.
Let me know what you think.

Add dialyzer for static code analysis

---

Dockerfile

While debugging issue https://github.com/appsignal/appsignal-elixir/issues/273 we found out that the bitwalker/alpine-elixir image returns the `'x86_64-unknown-linux-gnu'` value for the `:erlang.system_info(:system_architecture)` call.
Turns out the bitwalker/alpine-erlang image returns the same value for `erlang:system_info(system_architecture).`.
Looking at the official Erlang Docker image (https://hub.docker.com/_/erlang/) I saw that they specify the build target during `./configure` step, using the output from `dpkg-architecture --query DEB_BUILD_GNU_TYPE`. Applied the same logic to the bitwalker/erlang image in order to have `erlang:system_info(system_architecture).` return the correct host triple.
With this change `erlang:system_info(system_architecture).` will return …

Build Erlang with musl target on Alpine Linux

---

Dockerfile

The image is based on Alpine Linux v3.7, but adds v3.6 repos. It creates some very creative error messages when you try to add new packages later down the chain.
**Examples:**
When trying to add nodejs-current and yarn:
```
ERROR: unsatisfiable constraints:
Huh? Error reporter did not find the broken constraints.
```
When: Trying to add python3
```
ERROR: unsatisfiable constraints:
libressl2.5-libssl-2.5.5-r0:
masked in: @main
satisfies: python3-3.6.1-r3[so:libssl.so.43]
python3-3.6.1-r3:
masked in: @main
satisfies: world[python3]
```

Update tagged Alpine repos to use same version as image base (v3.7)

---

Dockerfile

Should be `dl-cdn` not `nl-cdn` in url.  Updated.

Fix edge repository url typo

---

Dockerfile

1. Updated erlang to 21.1 
2. Dropped the @edge tag from pcre, it fails to build otherwise.
3. added "--update --available" to the apk upgrade command to make sure it always has the latest copy of available packages and will upgrade all system packages.
4. Merged multiple apk add commands into single.

Update erlang version and consolidate 'apk add' statements

---

VERSION

@bitwalker A new patch version of erlang has been released.
https://erlang.org/download/OTP-23.2.5.README

chore(ERLANG_VERSION): Update to 23.2.5

---

Dockerfile
VERSION

@bitwalker The maintainers of Alpine Linux have released a new patch version. This release mainly includes updates to packages and fixes a CVE in OpenSSL.
https://www.openssl.org/news/secadv/20210216.txt
https://git.alpinelinux.org/cgit/aports/log/?h=v3.13.2

chore(ALPINE_VERSION): Update to 3.13.2

---

Makefile

@bitwalker It looks like we have an issue with the build pipeline as we are pushing the `build` section of the Dockerfile to Docker hub. For some background here is what I ran into and how I debugged the issue.
I came across production builds that were no longer working. I was getting an error when compiling elixir that essentially boiled down to the system telling me that erlang was not installed. I thought this was odd as everything looked good to me when we made the changes to get buildx up and running. So I created two debug Dockerfiles with the most recent version of alpine-erlang and the most recent working version (which is v23.2.2). One thing I noticed off the bat was the working version's image size was much smaller than the non working version (371MB vs 764MB). When I executed …

bugfix(Release): Do not use build as the target

---

Dockerfile
VERSION

@bitwalker A recent patch version of erlang has been released.
https://erlang.org/download/OTP-23.3.3.README

chore(ERLANG_VERSION): Update to 23.3.3

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker Updates to newest version of Alpine and Erlang.
https://erlang.org/download/OTP-24.0.5.README
https://alpinelinux.org/posts/Alpine-3.14.1-released.html

chore(ALPINE + ERLANG): Update to alpine 3.14.1 and erlang 24.0.5

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker Updates to erlang 24.0.6 and alpine 3.14.2
https://alpinelinux.org/posts/Alpine-3.14.2-released.html
https://erlang.org/download/OTP-24.0.6.README

chore(ALPINE + ERLANG): Update to alpine 3.14.2 and erlang 24.0.6

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker Updates alpine to the latest released version.
https://alpinelinux.org/posts/Alpine-3.14.3-released.html

chore(Alpine): Update to version 3.14.3

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker Updates erlang to 24.1.5 and 23.3.4.9. 
https://erlang.org/download/OTP-23.3.4.9.README
https://erlang.org/download/OTP-24.1.5.README

chore(Erlang): Update to version 24.1.5

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker Updates erlang and alpine to most recent versions.
https://alpinelinux.org/posts/Alpine-3.15.0-released.html
https://erlang.org/download/OTP-24.1.6.README
https://erlang.org/download/OTP-24.1.7.README

chore(ALPINE + ERLANG): Update to alpine 3.15.0 and erlang 24.1.7

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker updates alpine and erlang to most recent versions.
https://alpinelinux.org/posts/Alpine-3.15.1-released.html
https://erlang.org/download/OTP-24.3.README
https://erlang.org/download/OTP-24.3.1.README
https://erlang.org/download/OTP-24.3.2.README

chore(ALPINE + ERLANG): Update to alpine 3.15.1 and erlang 24.3.2

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker Updates Alpine linux to 3.15.2. May take a sec for docker images to be built.
https://alpinelinux.org/posts/Alpine-3.15.2-released.html

chore(Alpine): Update to version 3.15.2

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker Updates erlang to 24.3.3 and 23.3.4.13
https://erlang.org/download/OTP-24.3.3.README
https://erlang.org/download/OTP-23.3.4.10.README
https://erlang.org/download/OTP-23.3.4.11.README
https://erlang.org/download/OTP-23.3.4.12.README
https://erlang.org/download/OTP-23.3.4.13.README

chore(ERLANG): Update to version 24.3.3

---

.github/workflows/ci.yml
VERSION

@bitwalker A new release of Alpine has been created to fix a CVE in busybox.
https://alpinelinux.org/posts/Alpine-3.12.12-3.13.10-3.14.6-3.15.4-released.html
https://security.alpinelinux.org/vuln/CVE-2022-28391

chore(Alpine): Update to version 3.15.4

---

.github/workflows/ci.yml
Dockerfile
VERSION

@bitwalker Updates to alpine 3.16.2 which fixes a CVE in zlib. 
https://security.alpinelinux.org/vuln/CVE-2022-37434

chore(Alpine): Update to version 3.16.2
